version: '3.4'

services:
  clickmysecret:
    image: clickmysecret:0.5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:3000
